
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package upl.parser.parser.automatic;

/** CUP generated interface containing symbol constants. */
public interface CupParserSym {
  /* terminals */
  public static final int ELSE = 19;
  public static final int SEMICOLON = 7;
  public static final int PLUS = 6;
  public static final int INT = 23;
  public static final int LEFT_BRACE = 4;
  public static final int LEFT_PAREN = 2;
  public static final int THEN = 18;
  public static final int EQUAL = 9;
  public static final int WHILE = 21;
  public static final int STAR = 8;
  public static final int END = 16;
  public static final int IDENTIFIER = 13;
  public static final int GREATER_EQUAL = 12;
  public static final int GREATER = 11;
  public static final int IF = 17;
  public static final int DO = 20;
  public static final int BEGIN = 15;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int PRINT = 22;
  public static final int error = 1;
  public static final int BOOL = 24;
  public static final int RIGHT_BRACE = 5;
  public static final int RIGHT_PAREN = 3;
  public static final int EQUAL_EQUAL = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LEFT_PAREN",
  "RIGHT_PAREN",
  "LEFT_BRACE",
  "RIGHT_BRACE",
  "PLUS",
  "SEMICOLON",
  "STAR",
  "EQUAL",
  "EQUAL_EQUAL",
  "GREATER",
  "GREATER_EQUAL",
  "IDENTIFIER",
  "NUMBER",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "DO",
  "WHILE",
  "PRINT",
  "INT",
  "BOOL"
  };
}

